AllCops:
  Rails:
    Enabled: true
  Metrics/LineLength:
    Enabled: false
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
