sudo: required

language: ruby
cache: bundler
rvm:
  - 2.4.4

services:
  - postgresql

notifications:
  slack: patagonia-mara:xaEjhNnxt9qqXGyyqyGXUfDF

before_install:
  - cp config/database.yml.example config/database.yml
  - gem update --system

install:
  - bin/bundle install --path vendor/bundle

before_script:
  - psql -c 'create database mara_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test

jobs:
  include:
    - stage: rspec
      script: bin/rake
    - stage: bundle exec brakeman
      script: brakeman
    - stage: bundler-audit
      script: bundle exec bundle-audit
    - stage: rubocop
      script:
        - var="$(bundle exec pronto run -r rubocop -c origin/master)"
        - echo $var
        - if [[ -z $var ]]; then exit 0; else exit 1; fi
    - stage: reek
      script:
        - var="$(bundle exec pronto run -r reek -c origin/master)"
        - echo $var
        - if [[ -z $var ]]; then exit 0; else exit 1; fi
    - stage: fasterer
      script:
        - var="$(bundle exec pronto run -r fasterer -c origin/master)"
        - echo $var
        - if [[ -z $var ]]; then exit 0; else exit 1; fi
