sudo: required

language: ruby

install:
  - bundle install --path vendor/bundle

before_script:
  - rake db:migrate RAILS_ENV=test
  - bundle audit update

jobs:
  include:
    - stage: brakeman
      script: brakeman
    - stage: bundler-audit
      script: bundle audit
    - stage: rspec
      script: rspec
