sudo: required

language: ruby
rvm:
  - 2.4.4

before_install:
  - gem update --system

install:
  - bin/bundle install --path vendor/bundle

before_script:
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - bin/bundle audit update

jobs:
  include:
    # - stage: brakeman
    #   script: bin/brakeman
    # - stage: bundler-audit
    #   script: bin/bundle audit
    - stage: rspec
      script: bin/rake
