sudo: required

language: ruby
rvm:
  - 2.4.4

services:
  - postgresql

before_install:
  - cp config/database.yml.example config/database.yml
  - gem update --system

install:
  - bin/bundle install --path vendor/bundle

before_script:
  - psql -c "CREATE USER mara WITH PASSWORD '';" -U postgres
  - gipsql -c 'create database mara_test;' -U postgres
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - bin/bundle audit update

jobs:
  include:
    # - stage: brakeman
    #   script: bin/brakeman
    # - stage: bundler-audit
    #   script: bin/bundle audit
    - stage: rspec
      script: bin/rake
